---
title: "Exercise 12"
author: "Lili Benitez"
date: "2024-04-19"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(naniar)
f<-"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/Mammal_lifehistories_v2.txt"
d<-read_tsv(f)
replace_with_na_all(d,   condition = ~.x == -999)
d<-d%>%
  select(-`litter size`, refs)

d_log<-d%>%
  mutate(across(where(is.numeric), log))

```

## Regression: 
Regress the (now log transformed) age [gestation(mo), weaning(mo), AFR(mo) (age at first reproduction), and max. life(mo) (maximum lifespan)] and mass [newborn(g) and wean mass(g)] variables on (now log transformed) overall body mass(g) and add the residuals to the dataframe as new variables (relGest, relWean, relAFR, relLife, relNewbornMass, and relWeaningMass).
```{r}
d_log<-d_log%>%
  mutate(mass=`mass(g)`, 
         weaning=`weaning(mo)`, 
         gestation)
m_gest<-lm(data=d_log, mass~`gestation(mo)`, na.action = na.exclude)# not padding NAs
relGest<-resid(m_gest)
m_w<-lm(data=d_log, mass~`weaning(mo)`, na.action=na.exclude)
relWean<-resid(m_w)
m_AFR<-lm(data=d_log, mass~`AFR(mo)`, na.action=na.exclude)
relAFR<-resid(m_AFR)
m_life<-lm(data=d_log, mass~`max. life(mo)`, na.action=na.exclude)
relLife<-resid(m_life)
m_new<-lm(data=d_log, mass~`newborn(g)`, na.action=na.exclude)
relNewbornMass<-resid(m_new)
m_w_m<-lm(data=d_log, mass~`wean mass(g)`, na.action=na.exclude)
relWeaningMass<-resid(m_w_m)

d_log<-d_log%>%
  mutate(relGest=relGest, 
        relWean=relWean,
        relAFR=relAFR,
        relLife=relLife,
        relNewbornMass=relNewbornMass,
        relWeaningMass=relWeaningMass )

summary(m1)


```